# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence

stages:
- gitlab-test
- lint
- test

###############################################################################
#################### actions
###############################################################################

# As a GitLab ci, we use the default template :)
sast:
  stage: gitlab-test
include:
- template: Security/SAST.gitlab-ci.yml
  allow_failure: false

yaml_lint:
  stage: lint
  image: $NEXUS_DOCKER_PROXY_ADDRESS/$DOCKER_IMAGE_YAML_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - yamllint -c ./.yamllint --list-files
    - yamllint -c ./.yamllint ./
  allow_failure: false
  retry: 2
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"

jinja_lint:
  stage: lint
  image: $NEXUS_DOCKER_PROXY_ADDRESS/$DOCKER_IMAGE_JINJA_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - "[ -f \"./templates/*.j2\" ] && j2lint ./templates/*.j2 --ignore S3 S7"
  allow_failure: false
  retry: 2
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"

ansible_lint:
  stage: lint
  image: $NEXUS_DOCKER_PROXY_ADDRESS/$DOCKER_IMAGE_ANSIBLE_LINT
  before_script:
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
  script:
    - ansible-lint --config=./.ansible-lint --exclude molecule --exclude tests ./*
  allow_failure: false
  retry: 2
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_BRANCH == "develop"

.molecule_test: &molecule_test
  stage: test
  image: $NEXUS_DOCKER_PROXY_ADDRESS/$DOCKER_IMAGE_DOCKER_MOLECULE
  variables:
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
  before_script:
    - "docker login -u \"$NEXUS_REPOS_USERNAME\" -p \"$NEXUS_REPOS_PASSWORD\" http://$NEXUS_DOCKER_PROXY_ADDRESS"
    - "python3 -m compileall /usr/lib/python3 -qq"
    - "cp ./.ansible.cfg /root/.ansible.cfg"
    # Fix weird ansible bug: https://github.com/trailofbits/algo/issues/1637
    # This probably happens due to gitlab-runner mounting the git repo into the container
    - "chmod o-w ."
    - "[ -f \"./molecule/$SCENARIO/requirements.yml\" ] && ansible-galaxy install -r ./molecule/$SCENARIO/requirements.yml --roles-path=./molecule/$SCENARIO/roles"
  script:
    - "molecule test --scenario-name $SCENARIO"
  allow_failure: false
  retry: 2
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
  needs:
    - "lint"

molecule_test_debian_11:
  <<: *molecule_test
  variables:
    SCENARIO: "cicd-debian-11"
  needs:
    - "lint"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
