---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include labocbz.prepare_host"
      tags:
        - "labocbz.prepare_host"
      vars:
        prepare_host__users: "{{ inv_prepare_host__users }}"
        prepare_host__packages_removed: "{{ inv_prepare_host__packages_removed }}"
        prepare_host__packages_installed: "{{ inv_prepare_host__packages_installed }}"
        prepare_host__system_users: "{{ inv_prepare_host__system_users }}"
      ansible.builtin.include_role:
        name: "labocbz.prepare_host"
