---
- name: "Converge"
  hosts: "cicd-ubuntu-22"
  tasks:

    - name: "Include tool.bootstrap_ssl_files"
      tags:
        - "tool.bootstrap_ssl_files"
      vars:
        bootstrap_ssl_files__user: "{{ inv_bootstrap_ssl_files__user }}"
        bootstrap_ssl_files__base_path: "{{ inv_bootstrap_ssl_files__base_path }}"
        bootstrap_ssl_files__ca_validity: "{{ inv_bootstrap_ssl_files__ca_validity }}"
        bootstrap_ssl_files__key_size: "{{ inv_bootstrap_ssl_files__key_size }}"
        bootstrap_ssl_files__root_ca: "{{ inv_bootstrap_ssl_files__root_ca }}"
        bootstrap_ssl_files__intermediates_ca: "{{ inv_bootstrap_ssl_files__intermediates_ca }}"
        bootstrap_ssl_files__end_certs: "{{ inv_bootstrap_ssl_files__end_certs }}"
        bootstrap_ssl_files__cert_validity: "{{ inv_bootstrap_ssl_files__cert_validity }}"
      ansible.builtin.include_role:
        name: "tool.bootstrap_ssl_files"
